@startuml
'https://plantuml.com/class-diagram

class GameMain {
    + runGame()
}
class GameController {

}
class GameIO {

}
class DatabaseHandler {

}
package Database <<Database>> {
class Room {
+ int id //primary key
+ text name
+ int inventory_id
}
class Door {
+ int id //primary key
+ int room1_id //index
+ int room2_id //index
}
class Item {
+ int id //primary key
+ int inventory_id
+ text name
+ text description
+ int value
}
class Npc {
+ int id //primary key
+ int sheet_id
+ int room_id
+ int inventory_id
+ int action_id
+ bool action_active
}
class NpcSheet {
+ int id
+ text name
+ text description
...
}
class Inventory {
+ int id
}
class Action {
+ int id
+ text speach
+ int parent_action_id
}
}
Action -- Action
Npc -- Action
Npc -- NpcSheet
GameMain *-- GameController
GameIO -right--* GameController
GameController *-- DatabaseHandler
Database -right--* DatabaseHandler
Inventory -left-- Room : inv_id
Inventory -- Npc : inv_id
Item -left-- Inventory : inv_id
Room -- Npc : room_id
Door -right-- Room : room1_id
Door -right-- Room : room2_id

@enduml