@startuml
'https://plantuml.com/class-diagram

class GameMain {
    + runGame()
}
class GameController {

}
class GameIO {

}
class DatabaseHandler {

}
package Database <<Database>> {
class Rooms {
+ int id //primary key
+ text name
+ int inventory_id
}
class Doors {
+ int id //primary key
+ int room1_id //index
+ int room2_id //index
}
class Items {
+ int id //primary key
+ int inventory_id
+ text name
+ text description
+ int value
}
class Npcs {
+ int id //primary key
+ text name
+ text description
+ int type
+ int room_id
+ int inventory_id
+ int action_id
+ bool action_active
}
class NpcType {
+ int id
...
}
class Inventory {
+ int id
}
class Action {
+ int id
+ text speach
+ int parent_action_id
}
}
Action -- Action
Npcs -- Action
Npcs -- NpcType
GameMain *-- GameController
GameIO -right--* GameController
GameController *-- DatabaseHandler
Database -right--* DatabaseHandler
Inventory -left--* Rooms : room_id
Inventory --* Npcs : npc_id
Items -left--* Inventory : item_id
Rooms *-- Npcs : room_id
Doors -right--* Rooms : room1_id
Doors -right--* Rooms : room2_id

@enduml