@startuml
'https://plantuml.com/class-diagram

class GameMain {
    + runGame()
}
class GameController {

}
class GameIO {

}
class DatabaseHandler {

}
package Database <<Database>> {
class Rooms {
+ int room_id //primary key
+ text name
}
class Doors {
+ int door_id //primary key
+ int room1_id //index
+ int room2_id //index
}
class Items {
+ int item_id //primary key
+ text name
+ text description
+ int value
}
class Npcs {
+ int npc_id //primary key
+ text name
+ int room_id
}
class Inventory {
+ int inventory_id
+ int item_id //index
+ int npc_id //index
+ int room_id //index
}
}

GameMain *-- GameController
GameIO -right--* GameController
GameController *-- DatabaseHandler
Database -right--* DatabaseHandler
Inventory -left--* Rooms : room_id
Inventory --* Npcs : npc_id
Items -left--* Inventory : item_id
Rooms *-- Npcs : room_id
Doors -right--* Rooms : room1_id
Doors -right--* Rooms : room2_id

@enduml